import {
  makeWASocket,
  useMultiFileAuthState,
  fetchLatestBaileysVersion,
  DisconnectReason,
  Browsers,
} from 'baileys'
import pino from 'pino'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

/**
 * Real WhatsApp pairing.
 *
 * This module reuses the exact pairing primitive the bot itself uses
 * (Baileys `sock.requestPairingCode`, see Digix/Crew.js) so the code shown
 * to the user is the genuine one generated by WhatsApp — never mocked.
 *
 * Baileys keeps a persistent WebSocket to WhatsApp, so this must run on a
 * long-lived Node process (`node server.js`), NOT a serverless function.
 * If the bot lives on its own server, set BOT_BACKEND_URL and this module
 * transparently proxies the real backend instead of opening a local socket.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SESSIONS_ROOT = path.join(__dirname, '..', 'sessionData', 'pairings')
const BOT_BACKEND_URL = (process.env.BOT_BACKEND_URL || '').replace(/\/$/, '')

const logger = pino({ level: 'silent' })

/**
 * Live sessions keyed by phone number.
 * { sock, status: 'waiting'|'connected'|'failed', code, error, createdAt }
 */
const sessions = new Map()

function cleanNumber(number) {
  return String(number || '').replace(/\D/g, '')
}

function validateNumber(number) {
  const clean = cleanNumber(number)
  if (!clean) throw new Error('Entre ton numéro WhatsApp avec l’indicatif pays.')
  if (clean.length < 8 || clean.length > 15) throw new Error('Ce numéro WhatsApp n’est pas valide.')
  return clean
}

/** WhatsApp codes are 8 chars; display them grouped as ABCD-EFGH. */
function formatCode(code) {
  if (!code) return code
  const raw = String(code).replace(/-/g, '')
  return raw.length === 8 ? `${raw.slice(0, 4)}-${raw.slice(4)}` : raw
}

/* ------------------------------------------------------------------ *
 * Public API                                                          *
 * ------------------------------------------------------------------ */

export async function startPairing(number) {
  const clean = validateNumber(number)
  if (BOT_BACKEND_URL) return proxyStartPairing(clean)
  return localStartPairing(clean)
}

export async function getSession(number) {
  const clean = cleanNumber(number)
  if (!clean) return null
  if (BOT_BACKEND_URL) return proxyGetSession(clean)

  const session = sessions.get(clean)
  if (!session) return null
  return { number: clean, status: session.status, code: session.code, error: session.error }
}

/* ------------------------------------------------------------------ *
 * Local Baileys implementation (the real thing)                       *
 * ------------------------------------------------------------------ */

async function localStartPairing(number) {
  const existing = sessions.get(number)

  // Reuse a live session that already holds a valid code.
  if (existing && existing.code && (existing.status === 'waiting' || existing.status === 'connected')) {
    return { number, code: existing.code, status: existing.status }
  }

  // Drop any stale socket before starting a fresh pairing.
  if (existing?.sock) {
    try {
      existing.sock.end(undefined)
    } catch {
      /* ignore */
    }
  }

  const authDir = path.join(SESSIONS_ROOT, number)
  fs.mkdirSync(authDir, { recursive: true })

  const session = {
    sock: null,
    status: 'waiting',
    code: null,
    error: null,
    createdAt: Date.now(),
  }
  sessions.set(number, session)

  const rawCode = await createSocketAndPair(number, authDir, session, false)
  session.code = formatCode(rawCode)

  return { number, code: session.code, status: session.status }
}

async function createSocketAndPair(number, authDir, session, isReconnect) {
  const { state, saveCreds } = await useMultiFileAuthState(authDir)
  const { version } = await fetchLatestBaileysVersion()

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: false,
    logger,
    browser: Browsers.ubuntu('Chrome'),
    markOnlineOnConnect: false,
    keepAliveIntervalMs: 15000,
    connectTimeoutMs: 60000,
  })

  session.sock = sock
  sock.ev.on('creds.update', saveCreds)

  sock.ev.on('connection.update', (update) => {
    const { connection, lastDisconnect } = update

    if (connection === 'open') {
      session.status = 'connected'
      session.error = null
      return
    }

    if (connection === 'close') {
      const statusCode = lastDisconnect?.error?.output?.statusCode

      // After the user enters the code, WhatsApp asks for a socket restart to
      // finish the handshake — reconnect to reach the real "connected" state.
      if (statusCode === DisconnectReason.restartRequired) {
        createSocketAndPair(number, authDir, session, true).catch((e) => {
          console.error('[v0] reconnect after pairing failed:', e?.message)
        })
        return
      }

      if (statusCode === DisconnectReason.loggedOut) {
        session.status = 'failed'
        session.error = 'Session déconnectée par WhatsApp. Recommence le pairing.'
        return
      }

      // Any close before a successful connection is a real failure.
      if (session.status !== 'connected') {
        session.status = 'failed'
        session.error = lastDisconnect?.error?.message || 'WhatsApp a fermé la connexion.'
      }
    }
  })

  // Only request a code on the first attempt for an unregistered number.
  if (!isReconnect && !state.creds.registered) {
    return requestCodeWhenReady(sock, number)
  }

  return session.code ? session.code.replace(/-/g, '') : null
}

/**
 * Request the real pairing code once the WebSocket is ready.
 * The first `connection.update` carrying `qr` means the socket is live and
 * WhatsApp will accept a `requestPairingCode` call. Requesting before that
 * point throws "Connection Closed", so we wait for the `qr` signal and only
 * use a long timeout as a hard failure — never as an early attempt.
 */
function requestCodeWhenReady(sock, number) {
  return new Promise((resolve, reject) => {
    let attempted = false
    let settled = false

    const timer = setTimeout(() => {
      if (!settled) {
        settled = true
        reject(new Error('WhatsApp n’a pas répondu à temps. Réessaie.'))
      }
    }, 30000)

    sock.ev.on('connection.update', async (update) => {
      if (settled || attempted || !update.qr) return
      attempted = true
      try {
        const code = await sock.requestPairingCode(number)
        if (!settled) {
          settled = true
          clearTimeout(timer)
          resolve(code)
        }
      } catch (e) {
        if (!settled) {
          settled = true
          clearTimeout(timer)
          reject(e instanceof Error ? e : new Error(String(e)))
        }
      }
    })
  })
}

/* ------------------------------------------------------------------ *
 * Proxy implementation (bot runs on its own persistent server)        *
 * ------------------------------------------------------------------ */

async function parseJson(response) {
  try {
    return await response.json()
  } catch {
    throw new Error('Le backend du bot n’a pas renvoyé de JSON valide.')
  }
}

async function proxyStartPairing(number) {
  const response = await fetch(`${BOT_BACKEND_URL}/api/pairing`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({ number }),
  })
  const data = await parseJson(response)
  if (!response.ok || data.ok === false) {
    throw new Error(data.error || data.message || `Erreur backend (${response.status}).`)
  }
  return {
    number,
    code: formatCode(data.code || data.pairingCode),
    status: data.status || 'waiting',
  }
}

async function proxyGetSession(number) {
  const response = await fetch(`${BOT_BACKEND_URL}/api/pairing?number=${encodeURIComponent(number)}`, {
    method: 'GET',
    headers: { Accept: 'application/json' },
  })
  if (response.status === 404) return null
  const data = await parseJson(response)
  if (!response.ok || data.ok === false) {
    throw new Error(data.error || data.message || `Erreur backend (${response.status}).`)
  }
  return {
    number,
    status: data.status || 'waiting',
    code: formatCode(data.code || data.pairingCode),
    error: data.error || null,
  }
}
