import {
  makeWASocket,
  useMultiFileAuthState,
  DisconnectReason,
  fetchLatestBaileysVersion,
} from 'baileys'
import pino from 'pino'
import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SESSIONS_DIR = path.join(__dirname, '..', 'sessionData', 'pairings')

if (!fs.existsSync(SESSIONS_DIR)) {
  fs.mkdirSync(SESSIONS_DIR, { recursive: true })
}

/**
 * In-memory registry of active pairing sessions.
 * number -> { status, code, error, sock, createdAt }
 * status: 'waiting' | 'connected' | 'failed'
 */
const sessions = new Map()

function sanitizeNumber(raw) {
  return String(raw || '').replace(/[^0-9]/g, '')
}

export function getSession(number) {
  const clean = sanitizeNumber(number)
  const s = sessions.get(clean)
  if (!s) return null
  return {
    number: clean,
    status: s.status,
    code: s.code,
    error: s.error,
    createdAt: s.createdAt,
  }
}

async function closeSession(clean) {
  const s = sessions.get(clean)
  if (s?.sock) {
    try {
      s.sock.ev.removeAllListeners()
      s.sock.ws?.close()
    } catch {
      // ignore teardown errors
    }
  }
}

/**
 * Starts a real WhatsApp pairing flow for the given number using Baileys,
 * reusing the same requestPairingCode mechanism as the bot in Digix/Crew.js.
 * Returns the real pairing code generated by WhatsApp.
 */
export async function startPairing(rawNumber) {
  const number = sanitizeNumber(rawNumber)

  if (!number || number.length < 8) {
    throw new Error('Numéro invalide. Entrez votre numéro avec l’indicatif pays (ex: 243xxxxxxxx).')
  }

  // Reuse a fresh waiting session's code if it already exists.
  const existing = sessions.get(number)
  if (existing && existing.status === 'waiting' && existing.code) {
    return { number, code: existing.code, status: existing.status }
  }

  // Reset any previous state for this number.
  await closeSession(number)
  const authDir = path.join(SESSIONS_DIR, number)
  try {
    if (fs.existsSync(authDir)) fs.rmSync(authDir, { recursive: true, force: true })
  } catch {
    // ignore
  }

  const { version } = await fetchLatestBaileysVersion()
  const { state, saveCreds } = await useMultiFileAuthState(authDir)

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: false,
    syncFullHistory: true,
    markOnlineOnConnect: true,
    logger: pino({ level: 'silent' }),
    keepAliveIntervalMs: 10000,
    connectTimeoutMs: 60000,
    generateHighQualityLinkPreview: true,
  })

  const record = {
    status: 'waiting',
    code: null,
    error: null,
    sock,
    createdAt: Date.now(),
  }
  sessions.set(number, record)

  sock.ev.on('creds.update', saveCreds)

  sock.ev.on('connection.update', (update) => {
    const { connection, lastDisconnect } = update

    if (connection === 'open') {
      record.status = 'connected'
      record.error = null
      console.log(`[v0] WhatsApp connected for ${number}`)
    } else if (connection === 'close') {
      const statusCode = lastDisconnect?.error?.output?.statusCode
      const loggedOut = statusCode === DisconnectReason.loggedOut
      // A restartRequired right after pairing is normal; keep waiting unless truly failed.
      if (record.status !== 'connected') {
        if (loggedOut) {
          record.status = 'failed'
          record.error = 'Session expirée ou refusée par WhatsApp. Réessayez.'
        }
      }
      console.log(`[v0] Connection closed for ${number} (status ${statusCode})`)
    }
  })

  // Request the REAL pairing code from WhatsApp once the socket is ready.
  return await new Promise((resolve, reject) => {
    let settled = false

    const timeout = setTimeout(async () => {
      if (settled) return
      settled = true
      try {
        if (!state.creds.registered) {
          console.log(`[v0] Requesting pairing code for ${number}`)
          const code = await sock.requestPairingCode(number)
          record.code = code
          record.status = 'waiting'
          console.log(`[v0] Pairing code for ${number}: ${code}`)
          resolve({ number, code, status: 'waiting' })
        } else {
          record.status = 'connected'
          resolve({ number, code: null, status: 'connected' })
        }
      } catch (e) {
        record.status = 'failed'
        record.error = e?.message || 'Échec de la génération du code.'
        console.error(`[v0] Pairing error for ${number}:`, e)
        reject(new Error(record.error))
      }
    }, 5000)

    // Guard: if the socket dies before we get a code.
    sock.ev.on('connection.update', (u) => {
      if (settled) return
      if (u.connection === 'close') {
        const statusCode = u.lastDisconnect?.error?.output?.statusCode
        if (statusCode === DisconnectReason.loggedOut) {
          settled = true
          clearTimeout(timeout)
          record.status = 'failed'
          record.error = 'WhatsApp a refusé la connexion. Vérifiez le numéro et réessayez.'
          reject(new Error(record.error))
        }
      }
    })
  })
}
